name: ${project.name}
version: ${project.version}
main: com.andavin.images.Images
authors: [ 'Andavin' ]
description: ${project.description}
website: ${project.url}
softdepend: [ 'Multiverse-Core', 'PlotSquared', 'ProtocolLib' ]
api-version: '1.13'
commands:
  nft:
    description: 'Manage custom images.'
    usage: '/<command> [create|delete]'